In [1]:
coefficient_matrix = [[2,2,1],[2,-1,2],[1,-1,2]]
constant_vector = [9,6,5]

- 다양한 Matrix 계산을 어떻게 만들 것 인가?
- 굉장히 큰 Matrix에 대한 표현
- 처리 속도 문제 – 파이썬은 Interpreter 언

#Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준
- 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원함
- 선형대수와 관련된 다양한 기능을 제공함
- C, C++, 포트란 등의 언어와 통합 가능

### 1\.ndarray

In [2]:
import numpy as np

In [3]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [4]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [5]:
type(test_array[3])

numpy.float64

In [6]:
test_array = np.array([1, 4, 5, "8"], float) # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.])

In [7]:
print(type(test_array[3]))	# Float Type으로 자동 형변환을 실시

<class 'numpy.float64'>


In [8]:
print(test_array.dtype)     # Array(배열) 전체의 데이터 Type을 반환함

float64


In [9]:
print(test_array.shape)     # Array(배열) 의 shape을 반환함

(4,)


Array shape(vector)
- Array (vector, matrix, tensor)의 크기, 형태 등에 대한 정보

In [10]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [11]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

- ndim – number of dimension
- size – data의 개수

In [12]:
np.array(tensor, int).ndim

3

In [13]:
np.array(tensor, int).size

48

- Ndarray의 single element가 가지는 data type
- 각 element가 차지하는 memory의 크기가 결정됨

In [14]:
np.array([[1,2,3,],[4.5,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [16]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

- nbytes – ndarray object의 메모리 크기를 반환함

In [17]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.float32).nbytes # 32bits = 4bytes -> 6 * 4bytes

24

In [18]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.int8).nbytes # 8bits = 1bytes -> 6 * 1bytes

6

In [19]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.float64).nbytes # 64bits = 8bytes -> 6 * 48bytes

48

###2\. Handling shape

In [20]:
test_matrix = [[1,2,3,4,],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

Array의 shape의 크기를 변경함 (element의 갯수는 동일)

In [21]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [22]:
np.array(test_matrix).reshape(8,).shape

(8,)

Array의 size만 같다면 다차원으로 자유로이 변형가능

In [23]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [24]:
np.array(test_matrix).reshape(-1,2).shape   # -1: size를 기반으로 row 개수 선정

(4, 2)

In [25]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [26]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

flatten
- 다차원 array를 1차원 array로 변환

In [27]:
test_matrix = [[[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

###3\. Indexing & Slicing

- List와 달리 이차원 배열에서 [0,0] 과 같은 표기법을 제공함
- Matrix 일경우 앞은 row 뒤는 column을 의미함

####Indexing

In [28]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)

[[1 2 3]
 [4 5 6]]


In [29]:
print(a[0,0]) # Two dimensional array representation #1

1


In [30]:
print(a[0][0]) # Two dimensional array representation #2

1


In [31]:
a[0,0] = 12 # Matrix 0,0 에 12 할당
print(a)

[[12  2  3]
 [ 4  5  6]]


In [32]:
a[0][0] = 5 # Matrix 0,0 에 12 할당
print(a)

[[5 2 3]
 [4 5 6]]


In [33]:
test_example = np.array([[1,2,3],[4.5,5,6]],int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
test_example[0][0]

1

In [35]:
test_example[0,0]

1

In [36]:
test_example[0,0] = 12  # Matrix 0,0에 12할당
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [37]:
test_example[0,0] = 5  # Matrix 0,0에 5할당
print(test_example)
print(test_example[0][0])

[[5 2 3]
 [4 5 6]]
5


####Slicing
- List와 달리 행과 열 부분을 나눠서 slicing이 가능함
- Matrix의 부분 집합을 추출할 때 유용함

In [38]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:,2:]     # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [39]:
a[1,1:3]    # 1 Row의 1열 ~ 2열

array([7, 8])

In [40]:
a[1:3]      # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [41]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [42]:
test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [43]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
test_example[:,2:]  # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [45]:
test_example[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [46]:
test_example[1:3]   # 1Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

###4\. Creation Function

In [47]:
np.arange(30)   # range: List의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
np.arange(0, 5, 0.5)    #Floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [49]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

zeros – 0으로 가득찬 ndarray 생성

In [50]:
np.zeros(shape=(10,), dtype=np.int8)    # 10 - Zero Vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [51]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ones – 1로 가득찬 ndarrary 생성
np.ones(shape, dtype, order)

In [52]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [53]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

empty – shape만 주어지고 비어있는 ndarray 생성
(memory initialization 이 되지 않음)

In [54]:
np.empty(shape=(10,),dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [55]:
np.empty((3,5))

array([[4.65971943e-310, 1.06099790e-312, 1.01855798e-312,
        9.54898106e-313, 1.10343781e-312],
       [1.01855798e-312, 1.23075756e-312, 1.08221785e-312,
        1.12465777e-312, 9.76118064e-313],
       [1.08221785e-312, 1.01855798e-312, 1.20953760e-312,
        4.44659081e-322, 0.00000000e+000]])

기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환


In [56]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [57]:
np.empty_like(test_matrix)

array([[94313775315520,              0,              0,              0,
                     0,              0],
       [             0,              0,              0,              0,
                     0,              0],
       [             0,              0,              0,              0,
                     0,              0],
       [             0,              0,              0,              0,
                     0,              0],
       [             0,              0,              0,              0,
                     0,              0]])

In [58]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

identity
- 단위 행렬(i 행렬)을 생성함

In [59]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [60]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

eye
- 대각선인 1인 행렬, k값의 시작 index의 변경이 가능

In [61]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [62]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.eye(3,5,k=2)     # k : start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

diag
- 대각 행렬의 값을 추출함

In [64]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
np.diag(matrix)

array([0, 4, 8])

In [66]:
np.diag(matrix, k=1)    # k : start index

array([1, 5])

random sampling 
- 데이터 분포에 따른 sampling으로 array를 생성

In [67]:
np.random.uniform(0,1,10).reshape(2,5)  # 균등분포

array([[0.46944465, 0.59792381, 0.96241546, 0.14695337, 0.07853764],
       [0.68451141, 0.63007349, 0.09461761, 0.55226687, 0.95967179]])

In [68]:
np.random.normal(0,1,10).reshape(2,5)   # 정규분포

array([[ 0.45000876,  0.43361923,  0.68809637, -1.47207233, -0.06337853],
       [ 0.13325563, -3.35278347, -1.31210487,  0.63090029, -0.79061865]])

###5\. Operation Functions

sum
- ndarray의 element들 간의 합을 구함, list의 sum 기능과 동일

In [69]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
test_array.sum(dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


55.0

axis
- 모든 operation function을 실행할 때, 기준이 되는 dimension 축

In [71]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [73]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [74]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [75]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [76]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

mean & std
- ndarray의 element들 간의 평균 또는 표준 편차를 반환

In [77]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
test_array.mean()

6.5

In [79]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [80]:
test_array.std()

3.452052529534663

In [81]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

Mathematical functions
- 그 외에도 다양한 수학 연산자를 제공함


In [82]:
from numpy.random.mtrand import exponential

In [83]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [84]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

concatenate
- Numpy array를 합치는 함수

In [85]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a)
print(b)
np.vstack((a,b))

[1 2 3]
[2 3 4]


array([[1, 2, 3],
       [2, 3, 4]])

In [86]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
print(a)
print(b)
np.hstack((a,b))

[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]


array([[1, 2],
       [2, 3],
       [3, 4]])

In [87]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
print(a)
print(b)
np.concatenate((a,b), axis=0)

[[1 2 3]]
[[2 3 4]]


array([[1, 2, 3],
       [2, 3, 4]])

In [88]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(a)
print(b)
np.concatenate((a,b.T), axis=1) # b.T -> b의 전치행렬

[[1 2]
 [3 4]]
[[5 6]]


array([[1, 2, 5],
       [3, 4, 6]])

###6\. Array operations

**Operations b/t arrays**
- Numpy는 array간의 기본적인 사칙 연산을 지원함

In [89]:
test_a = np.array([[1,2,3],[4,5,6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [90]:
test_a + test_a     # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [91]:
test_a - test_a     # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
test_a * test_a     # Matrix * Matrix 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

**Element-wise operations**
- Array간 shape이 같을 때 일어나는 연산

In [93]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

**Dot product**
- Matrix의 기본 연산
- dot 함수 사용

In [94]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
print(test_a)

[[1 2 3]
 [4 5 6]]


In [95]:
print(test_b)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [96]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

**transpose**
- transpose 또는 T attribute 사용


In [97]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [101]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

**broadcasting**
- Shape이 다른 배열 간 연산을 지원하는 기능

In [102]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [103]:
test_matrix + scalar    # Matrix - Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [104]:
test_matrix - scalar    # Matrix - Scalar 뺄셈

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [105]:
test_matrix * 5    # Matrix - Scalar 곱셈

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [106]:
test_matrix / 5    # Matrix - Scalar 나눗셈

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [107]:
test_matrix // 0.2   # Matrix - Scalar 몫

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [108]:
test_matrix ** 2   # Matrix - Scalar 제곱

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [109]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)

In [110]:
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [111]:
test_vector

array([10, 20, 30])

In [112]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

**Numpy performance**
- 일반적으로 속도는 아래 순  
for loop < list comprehension < numpy
- 100,000,000 번의 loop이 돌 때 약 약 4배 이상의 성능 차이를 보임
- Numpy는 C로 구현되어 있어, 성능을 확보하는 대신
- 파이썬의 가장 큰 특징인 dynamic typing을 포기함
- 대용량 계산에서는 가장 흔히 사용됨
- Concatenate 처럼 계산이 아닌, 할당에서는 연산 속도의 이점이 없음

In [113]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result

iternation_max = 100000000
vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

1 loop, best of 5: 14.4 s per loop
1 loop, best of 5: 12.3 s per loop
1 loop, best of 5: 273 ms per loop


###7\. Comparisons

**All & Any**
- Array의 데이터 전부(and) 또는 일부(or)가 조건에 만족하는지 반환

In [116]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.any(a > 5), np.any(a < 0)    # any : 하나라도 조건에 만족한다면 true

(True, False)

In [118]:
np.all(a > 5), np.all(a < 10)   # all : 모두 조건에 만족한다면 true

(False, True)

**Comparison operation #1**
- Numpy는 배열의 크기가 동일 할 때
element간 비교의 결과를 Boolean type으로 반환하여 돌려줌

In [119]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
test_a > test_b

array([False,  True, False])

In [120]:
test_a == test_b

array([False, False, False])

In [121]:
(test_a > test_b).any() # any : 하나라도 조건에 만족한다면 true

True

In [122]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3)    # and 조건의 condition

array([ True, False, False])

In [125]:
b = np.array([True, False, True], bool)
np.logical_not(b)   # NOT 조건의 condition

array([False,  True, False])

In [126]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

**np.where**

In [127]:
np.where(a > 0, 3, 2)   # where(condition, True, False)

array([3, 3, 2])

In [128]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.where(a > 5)

(array([6, 7, 8, 9]),)

In [130]:
a = np.array([1, np.NaN, np.Inf],float)
np.isnan(a)

array([False,  True, False])

In [131]:
np.NaN

nan

In [133]:
type(np.NaN)

float

In [132]:
np.Inf

inf

In [134]:
type(np.Inf)

float

**argmax & argmin**

In [137]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)  # array내 최대값 또는 최소값의 index를 반환함

(5, 0)

In [139]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)  # axis 기반 반환

(array([3, 1, 1]), array([0, 0, 2, 2]))

**Boolean & Fancy Index**

**boolean index**
- numpy는 배열은 특정 조건에 따른 값을 배열 형태로 추출 할 수 있음
- Comparison operation 함수들도 모두 사용가능

In [141]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [142]:
test_array[test_array > 3]  # 조건이 True인 index의 element만 추출

array([4., 8., 9., 7.])

In [144]:
condition = test_array > 3
test_array[condition]

array([4., 8., 9., 7.])

**fancy index**
- numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [145]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1],int) #반드시 integer로 선언
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [146]:
a.take(b)   # take 함수 : bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

- Matrix 형태의 데이터도가능

In [147]:
a = np.array([[1,4],[9,16]],float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c]  # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

###8\. Numpy data/io

**loadtxt & savetxt**
- Text type의 데이터를 읽고, 저장하는 기능

In [149]:
a = np.loadtxt("./populations.txt")
a[:10]

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.]])

In [150]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [151]:
np.savetxt('int_data.csv', a_int, delimiter=",")

**numpy object - npy**
- Numpy object (pickle) 형태로 데이터를 저장하고 불러옴
- Binary 파일 형태로 저장함

In [152]:
np.save("npy_test", arr=a_int)

In [153]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])