In [ ]:
coefficient_matrix = [[2,2,1],[2,-1,2],[1,-1,2]]
constant_vector = [9,6,5]

- 다양한 Matrix 계산을 어떻게 만들 것 인가?
- 굉장히 큰 Matrix에 대한 표현
- 처리 속도 문제 – 파이썬은 Interpreter 언

#Numpy
- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 사실상의 표준
- 한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
- 일반 List에 비해 빠르고, 메모리 효율적
- 반복문 없이 데이터 배열에 대한 처리를 지원함
- 선형대수와 관련된 다양한 기능을 제공함
- C, C++, 포트란 등의 언어와 통합 가능

### 1\.ndarray

In [ ]:
import numpy as np

In [ ]:
test_array = np.array([1, 4, 5, 8], float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [ ]:
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [ ]:
type(test_array[3])

numpy.float64

In [ ]:
test_array = np.array([1, 4, 5, "8"], float) # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.])

In [ ]:
print(type(test_array[3]))	# Float Type으로 자동 형변환을 실시

<class 'numpy.float64'>


In [ ]:
print(test_array.dtype)     # Array(배열) 전체의 데이터 Type을 반환함

float64


In [ ]:
print(test_array.shape)     # Array(배열) 의 shape을 반환함

(4,)


Array shape(vector)
- Array (vector, matrix, tensor)의 크기, 형태 등에 대한 정보

In [ ]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [ ]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
          [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

- ndim – number of dimension
- size – data의 개수

In [ ]:
np.array(tensor, int).ndim

3

In [ ]:
np.array(tensor, int).size

48

- Ndarray의 single element가 가지는 data type
- 각 element가 차지하는 memory의 크기가 결정됨

In [ ]:
np.array([[1,2,3,],[4.5,5,6]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [ ]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

- nbytes – ndarray object의 메모리 크기를 반환함

In [ ]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.float32).nbytes # 32bits = 4bytes -> 6 * 4bytes

24

In [ ]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.int8).nbytes # 8bits = 1bytes -> 6 * 1bytes

6

In [ ]:
np.array([[1,2,3,],[4.5,"5","6"]], dtype=np.float64).nbytes # 64bits = 8bytes -> 6 * 48bytes

48

###2\. Handling shape

In [ ]:
test_matrix = [[1,2,3,4,],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

Array의 shape의 크기를 변경함 (element의 갯수는 동일)

In [ ]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [ ]:
np.array(test_matrix).reshape(8,).shape

(8,)

Array의 size만 같다면 다차원으로 자유로이 변형가능

In [ ]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [ ]:
np.array(test_matrix).reshape(-1,2).shape   # -1: size를 기반으로 row 개수 선정

(4, 2)

In [ ]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [ ]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

flatten
- 다차원 array를 1차원 array로 변환

In [ ]:
test_matrix = [[[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

###3\. Indexing & Slicing

- List와 달리 이차원 배열에서 [0,0] 과 같은 표기법을 제공함
- Matrix 일경우 앞은 row 뒤는 column을 의미함

####Indexing

In [ ]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a[0,0]) # Two dimensional array representation #1

1


In [ ]:
print(a[0][0]) # Two dimensional array representation #2

1


In [ ]:
a[0,0] = 12 # Matrix 0,0 에 12 할당
print(a)

[[12  2  3]
 [ 4  5  6]]


In [ ]:
a[0][0] = 5 # Matrix 0,0 에 12 할당
print(a)

[[5 2 3]
 [4 5 6]]


In [ ]:
test_example = np.array([[1,2,3],[4.5,5,6]],int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
test_example[0][0]

1

In [ ]:
test_example[0,0]

1

In [ ]:
test_example[0,0] = 12  # Matrix 0,0에 12할당
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [ ]:
test_example[0,0] = 5  # Matrix 0,0에 5할당
print(test_example)
print(test_example[0][0])

[[5 2 3]
 [4 5 6]]
5


####Slicing
- List와 달리 행과 열 부분을 나눠서 slicing이 가능함
- Matrix의 부분 집합을 추출할 때 유용함

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
a[:,2:]     # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
a[1,1:3]    # 1 Row의 1열 ~ 2열

array([7, 8])

In [ ]:
a[1:3]      # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

In [ ]:
test_example = np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]], int)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
test_example[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [ ]:
test_example = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
test_example[:,2:]  # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
test_example[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [ ]:
test_example[1:3]   # 1Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10]])

###4\. Creation Function

In [ ]:
np.arange(30)   # range: List의 range와 같은 효과, integer로 0부터 29까지 배열 추출

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(0, 5, 0.5)    #Floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

zeros – 0으로 가득찬 ndarray 생성

In [ ]:
np.zeros(shape=(10,), dtype=np.int8)    # 10 - Zero Vector 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros((2,5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

ones – 1로 가득찬 ndarrary 생성
np.ones(shape, dtype, order)

In [ ]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

empty – shape만 주어지고 비어있는 ndarray 생성
(memory initialization 이 되지 않음)

In [ ]:
np.empty(shape=(10,),dtype=np.int8)

array([ 80, -74, -51,  13,  32,  86,   0,   0, 120, -31], dtype=int8)

In [ ]:
np.empty((3,5))

array([[4.67858892e-310, 1.06099790e-312, 1.01855798e-312,
        9.54898106e-313, 1.08221785e-312],
       [1.03977794e-312, 1.23075756e-312, 1.12465777e-312,
        1.10343781e-312, 9.76118064e-313],
       [1.14587773e-312, 1.14587773e-312, 1.12465777e-312,
        3.44981226e+175, 4.84427217e+276]])

기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환


In [ ]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:
np.empty_like(test_matrix)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

identity
- 단위 행렬(i 행렬)을 생성함

In [ ]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

eye
- 대각선인 1인 행렬, k값의 시작 index의 변경이 가능

In [ ]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,5,k=2)     # k : start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

diag
- 대각 행렬의 값을 추출함

In [ ]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.diag(matrix)

array([0, 4, 8])

In [ ]:
np.diag(matrix, k=1)    # k : start index

array([1, 5])

random sampling 
- 데이터 분포에 따른 sampling으로 array를 생성

In [ ]:
np.random.uniform(0,1,10).reshape(2,5)  # 균등분포

array([[0.76838999, 0.87324163, 0.10077962, 0.99132928, 0.8813546 ],
       [0.13057647, 0.42992147, 0.16476082, 0.29135762, 0.76826743]])

In [ ]:
np.random.normal(0,1,10).reshape(2,5)   # 정규분포

array([[ 6.75174206e-04, -4.17264428e-01,  1.76491496e+00,
         4.94308220e-01, -6.67142036e-01],
       [ 9.84105334e-01, -2.46271471e-01,  3.92337102e-01,
         2.11548530e+00, -8.44983193e-01]])

###5\. Operation Functions

sum
- ndarray의 element들 간의 합을 구함, list의 sum 기능과 동일

In [ ]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
test_array.sum(dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


55.0

axis
- 모든 operation function을 실행할 때, 기준이 되는 dimension 축

In [ ]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [ ]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [ ]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [ ]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

mean & std
- ndarray의 element들 간의 평균 또는 표준 편차를 반환

In [ ]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
test_array.mean()

6.5

In [ ]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [ ]:
test_array.std()

3.452052529534663

In [ ]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

Mathematical functions
- 그 외에도 다양한 수학 연산자를 제공함


In [ ]:
from numpy.random.mtrand import exponential

In [ ]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [ ]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

concatenate
- Numpy array를 합치는 함수

In [ ]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a)
print(b)
np.vstack((a,b))

[1 2 3]
[2 3 4]


array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
print(a)
print(b)
np.hstack((a,b))

[[1]
 [2]
 [3]]
[[2]
 [3]
 [4]]


array([[1, 2],
       [2, 3],
       [3, 4]])

In [ ]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
print(a)
print(b)
np.concatenate((a,b), axis=0)

[[1 2 3]]
[[2 3 4]]


array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
print(a)
print(b)
np.concatenate((a,b.T), axis=1) # b.T -> b의 전치행렬

[[1 2]
 [3 4]]
[[5 6]]


array([[1, 2, 5],
       [3, 4, 6]])